language: node_js
node_js:
  - "10"
branches:
  only:
  - master
  - v0.11.6
env:
  - NODE_ENV=development

addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - npm cache --force clean
  - npm install -g firebase-tools

script:
  - echo "Static assets only"

deploy:
  - provider: firebase
    skip_cleanup: true
    message: "Deploying v0.11.dev-$TRAVIS_BUILD_NUMBER-ALPHA"
    token:
      secure: "nnxGs81E5zkTjcKZCwpvsikjNlv7lTuKEdzYd3TM0mthJnlvRURTfSHcrC/U+kj23U+ZiooXcCo8ITKZmGvKs1dzg5ag4mcoxIyWy0CA0HfbKYQIqCCij0+4au4vK9gNjutk4Wun8peXl8oSB90F1A6DdooDm/GiNUidyXSlvZk="
    on:
      branch: v0.11.6
  - provider: firebase
    skip_cleanup: true
    message: "Deploying v0.11-$TRAVIS_BUILD_NUMBER-ALPHA"
    token:
      secure: "nnxGs81E5zkTjcKZCwpvsikjNlv7lTuKEdzYd3TM0mthJnlvRURTfSHcrC/U+kj23U+ZiooXcCo8ITKZmGvKs1dzg5ag4mcoxIyWy0CA0HfbKYQIqCCij0+4au4vK9gNjutk4Wun8peXl8oSB90F1A6DdooDm/GiNUidyXSlvZk="
    on:
      branch: master
