language: node_js
node_js:
  - "10"
branches:
  only:
  - master
  - v0.11.6
env:
  - NODE_ENV=development
  - secure: "AdKTawqqAdEQ2Zdz4mJKqxAfvBazuAtWwo9Oc7OVnUykscgsKXh1OM73Pwo5TBT4+EhOV91TlQFx/fUESkhbcCLh1vIwrtAn551yxVftQEFzwVBzG/8J47No14MI+Ze3mJfkPMfpr1AQeckozYSeGHO9gAlEnZozpk1qMOeicsE="

addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - npm cache --force clean
  - npm install -g firebase-tools

script:
  - echo "Static assets only"

deploy:
  - provider: script
    skip_cleanup: true
    message: "Deploying v0.11.dev-$TRAVIS_BUILD_NUMBER-ALPHA"
    script: sh ./scripts/deployment/dev.sh
    on:
      branch: v0.11.6
  - provider: firebase
    skip_cleanup: true
    message: "Deploying v0.11-$TRAVIS_BUILD_NUMBER-ALPHA"
    script: sh ./scripts/deployment/prod.sh
    on:
      branch: master
